// This file will be generated by your data manager
// You can also manually edit this file to add more paintings

export interface PaintingData {
  id: string
  title: string
  year: string
  realImagePath: string
  fakeImagePath: string
  difficulty: "Easy" | "Medium" | "Hard" | "Expert"
  points: number
  description: string
  techniques: string[]
  isActive: boolean
}

// Import your generated data here
// This will be replaced with your actual data
export const paintingsData: PaintingData[] = [
  // Your generated paintings will go here
  // Example:
  // {
  //   id: "1",
  //   title: "The Starry Night",
  //   year: "1889",
  //   realImagePath: "/paintings/real/starry-night.jpg",
  //   fakeImagePath: "/paintings/ai/starry-night-ai.jpg",
  //   difficulty: "Medium",
  //   points: 20,
  //   description: "Compare the real Van Gogh 'The Starry Night' with its AI-generated version.",
  //   techniques: ["Post-Impressionism", "Impasto", "Brushwork analysis"],
  //   isActive: true
  // }
]

// Function to get random painting for game
export function getRandomPainting(): PaintingData | null {
  const activePaintings = paintingsData.filter((p) => p.isActive)
  if (activePaintings.length === 0) return null

  const randomIndex = Math.floor(Math.random() * activePaintings.length)
  return activePaintings[randomIndex]
}

// Function to get paintings by difficulty
export function getPaintingsByDifficulty(difficulty: string): PaintingData[] {
  return paintingsData.filter((p) => p.difficulty === difficulty && p.isActive)
}
